dataset:
  data_path: data/
  dev_ratio: 0.2
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: transport
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 50
  train_ratio: 0.8
device: cuda:0
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_transport_2020-Mar-31-16-44-57_14804
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 128
  has_attention: true
  hidden_dim: 128
  is_sym: true
  max_num_nodes: 361
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 10
  sample_stride: 1
run_id: '14804'
runner: GranRunner
save_dir: exp/GRAN\GRANMixtureBernoulli_transport_2020-Mar-31-16-44-57_14804
seed: 1234
test:
  batch_size: 20
  better_vis: true
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 20
  num_vis: 20
  num_workers: 0
  test_model_dir: C:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\exp\GRAN\GRANMixtureBernoulli_transport_2020-Mar-31-15-07-48_22628
  test_model_name: model_snapshot_0000020.pth
  vis_num_row: 5
train:
  batch_size: 1
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.3
  lr_decay_epoch:
  - 100000000
  max_epoch: 3000
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: null
  resume_epoch: 5000
  resume_model: model_snapshot_0005000.pth
  shuffle: true
  snapshot_epoch: 10
  valid_epoch: 10
  wd: 0.0
use_gpu: true
use_horovod: false
