---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: transport
  data_path: data\us_cities_2
  node_order: all # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 40 # number of subgraphs per mini-batch
  num_fwd_pass: 4
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: true
model:
  name: GRANMixtureBernoulli
  num_mix_component: 8
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 100
  hidden_dim: 64 # Skal være ens med embedding_Dim
  embedding_dim: 64
  num_GNN_layers: 4
  num_GNN_prop: 1
  num_canonical_order: 5
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.3
  lr_decay_epoch: [2000] # no decay
  num_workers: 0
  max_epoch: 30000
  batch_size: 4
  display_iter: 100
  snapshot_epoch: 500
  valid_epoch: 100
  lr: 1.0e-2
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: False
  resume_epoch: 10000
  resume_dir: C:\Users\johanoliver\Documents\GitHub\GRAN\exp\GRAN\GRANMixtureBernoulli_transport_2020-Jun-08-20-51-36_9872
  resume_model: model_snapshot_0001500.pth
test:
  batch_size: 2
  num_workers: 0
  num_test_gen: 8 # number of generated samples
  is_vis: true
  is_single_plot: false # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 10
  vis_num_row: 5 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: C:\Users\johanoliver\Documents\GitHub\GRAN\exp\GRAN\GRANMixtureBernoulli_transport_2020-Jun-08-21-19-13_896
  test_model_name: model_snapshot_0000500.pth
attributes:
  x:
   node_feature: true  #If false, it must be an edge feature
   model: true #Whether the attribute is to be generated in the model, or just be included in the data
   regression: true #Whether it is regression, or classification
  y:
   node_feature: true  #If false, it must be an edge feature
   model: true #Whether the attribute is to be generated in the model, or just be included in the data
   regression: true #Whether it is regression, or classification
  # edge:
  #  node_feature: false  #If false, it must be an edge feature
  #  model: true #Whether the attribute is to be generated in the model, or just be included in the data
  #  regression: true #Whether it is regression, or classification